
FEATURES = 'features'
FEATURE_LENGTH = 'feature_length'
LABELS = 'labels'
LABEL_LENGTH = 'label_length'
VOCAB = 'vocab.npy'
DATA_CONFIG = 'data_config.json'
SPEAKER_ID = 'speaker_id'
UTTERANCE_ID = 'utterance_id'
RAW_TEXT = 'raw_text'
